name: Deploy VK Mini App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать проект
        uses: actions/checkout@v4

      - name: Установить Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Загрузить приложение на VK Hosting
        run: printf 'y\ny\n' | npm exec --yes --package=@vkontakte/vk-miniapps-deploy@latest -- vk-miniapps-deploy
        env:
          MINI_APPS_ACCESS_TOKEN: ${{ secrets.VK_MINI_APPS_ACCESS_TOKEN }}
          MINI_APPS_ENVIRONMENT: production
          CI_URLS: true